title: Rashi Pant
description: >
  Researcher in cognitive neuroscience
  
url: https://rashipant.github.io
baseurl: ""

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

author: Rashi Pant
social: 
  name: Rashi Pant
  links:
    - https://github.com/rashipant
    - https://www.linkedin.com/in/rashi-pant-2410279a/
    - https://scholar.google.com/citations?user=3L4I5YwAAAAJ&hl=en

logo: /assets/images/Pant_Rashi.jpg
